export enum Algorithms {
    LINEAR_REGRESSION = 1,
    LINEAR_REGRESSION_BAGGING,
    IBK,
    ZEROR,
    M5P,
    M5P_BAGGING,
    M5RULES,
    DECISION_STUMP,
    DECISION_STUMP_BAGGING,
    LIBSVM,
    LIBSVM_BAGGING
}
